language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
script: yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET_NAME    
  region: $AWS_DEFAULT_REGION
  local_dir: build
  skip_cleanup: true
